In [ ]:
import pandas as pd

melb_df = pd.read_csv('data/melb_data_fe.csv')

melb_df['Date'] = pd.to_datetime(melb_df['Date'])
melb_df.info()
melb_df.head()

In [11]:
quarter_melb = melb_df['Date'].dt.quarter.value_counts()
display(quarter_melb)

Date
3    4873
2    4359
4    2329
1    2019
Name: count, dtype: int64

In [ ]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
display(melb_df.info())

In [ ]:
melb_df.sort_values(by='Price').head(10)

In [ ]:
melb_df.sort_values(by='Date', ascending=False)

In [ ]:
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]
melb_df.sort_values(by=['Price', 'Distance']).loc[::10, ['Distance', 'Price']]

In [ ]:
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

In [25]:
filtered = melb_df[melb_df['Rooms'] > 5].copy()

filtered.sort_values(inplace=True, by=['Rooms'])

filtered.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
47,Airport West,6,house,725000.0,SP,Barry,2016-07-05,13.5,3042,6,...,144.87350,Western Metropolitan,3464,12.4000,-0.679862,7,36,1,Rd,0
10043,other,6,house,1050000.0,S,other,2017-06-24,35.4,3198,6,...,145.13050,South-Eastern Metropolitan,8077,23.3125,-0.279227,6,47,5,St,1
9803,Box Hill,6,house,2150500.0,PI,McGrath,2017-06-24,10.9,3128,6,...,145.12748,Eastern Metropolitan,4605,8.4000,-0.723684,6,47,5,St,1
9591,other,6,house,935000.0,S,other,2017-06-17,18.0,3037,6,...,144.73779,Western Metropolitan,5556,7.8750,-0.692683,6,47,5,Dr,1
9582,Hawthorn East,6,house,2200000.0,VB,Jellis,2017-06-17,6.2,3123,6,...,145.05542,Southern Metropolitan,6482,8.4000,-0.663102,6,47,5,Rd,1