In [48]:
import pandas as pd
covid_data = pd.read_csv('D:/Python обучение/Pandas_learning/Pandas/Pandas_stady/data/covid_data/covid_data.csv')
display(covid_data.head())

         date province/state country  confirmed  deaths  recovered
0  01/22/2020          Anhui   China        1.0     0.0        0.0
1  01/22/2020        Beijing   China       14.0     0.0        0.0
2  01/22/2020      Chongqing   China        6.0     0.0        0.0
3  01/22/2020         Fujian   China        1.0     0.0        0.0
4  01/22/2020          Gansu   China        0.0     0.0        0.0

In [49]:
vaccinations_data = pd.read_csv('D:/Python обучение/Pandas_learning/Pandas/Pandas_stady/data/covid_data/country_vaccinations.csv')
vaccinations_data = vaccinations_data[
    ['country', 'date', 'total_vaccinations', 
     'people_vaccinated', 'people_vaccinated_per_hundred',
     'people_fully_vaccinated', 'people_fully_vaccinated_per_hundred',
     'daily_vaccinations', 'vaccines']
]
#display(vaccinations_data)

In [50]:
covid_data = covid_data.groupby(
    ['date', 'country'], 
    as_index=False
)[['confirmed', 'deaths', 'recovered']].sum()


covid_data['date'] = pd.to_datetime(covid_data['date'])

In [51]:
vaccinations_data["active"] = covid_data['confirmed'] - covid_data['deaths'] - covid_data['recovered']

In [52]:
covid_data = covid_data.sort_values(by=['country', 'date'])
covid_data['daily_confirmed'] = covid_data.groupby('country')['confirmed'].diff()
covid_data['daily_deaths'] = covid_data.groupby('country')['deaths'].diff()
covid_data['daily_recovered'] = covid_data.groupby('country')['recovered'].diff()

In [53]:
vaccinations_data['date'] = pd.to_datetime(vaccinations_data['date'])

In [ ]:
display(covid_data['date'].sort_values())
display(vaccinations_data['date'].sort_values())
display(vaccinations_data['date'].max())

In [ ]:
display(covid_data)
display(vaccinations_data)

In [67]:
covid_df = covid_data.merge(
    vaccinations_data,
    how='left'
)
display(covid_df)

,date,country,confirmed,deaths,recovered,daily_confirmed,daily_deaths,daily_recovered,total_vaccinations,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,vaccines,active
0,2020-02-24,Afghanistan,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25,Afghanistan,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26,Afghanistan,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27,Afghanistan,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28,Afghanistan,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86780,2020-03-12,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86781,2020-03-14,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86782,2020-03-15,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86783,2020-03-16,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86784,2020-03-17,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
#covid_df['death_rate'] =  covid_df['deaths'].sum() / covid_df['confirmed'].sum()  * 100
us_covid = covid_df[covid_df['country'] == 'United States']
rus_covid = covid_df[covid_df['country'] == 'Russia']
us_covid['death_rate'] = us_covid['deaths'] / us_covid['confirmed'] * 100 
display(us_covid['death_rate'].max())
covid_df['recover_rate'] = covid_df['recovered'] / covid_df['confirmed']  * 100
display(rus_covid['recover_rate'].mean())

C:\Users\Arhan\AppData\Local\Temp\ipykernel_19260\3469259318.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_covid['death_rate'] = us_covid['deaths'] / us_covid['confirmed'] * 100

7.18954248366013

67.06273489477655